version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    networks:
      - internal
    volumes:
      - ./api:/application
      - ./sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"

  php-fpm:
    build: sourcefiles/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm

    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./api:/application
      - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - internal

  pgsql:
    image: 'postgres:15'
    env_file:
      - api/.env
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-password}'
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-laravel}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'pgsql-storage:/var/lib/postgresql/data'
      - './pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - internal



volumes:
 pgsql-storage:
    driver: local
networks:
  internal:
    driver: bridge
